//! Every published cross-file code. TS-53 compares generated explain pages
//! against the literals in `CrossFileDiagnostic::code`, so an omitted or stale
//! entry fails the mechanically enumerated producer coverage check.

use super::CrossFileDiagnostic;

impl CrossFileDiagnostic {
    /// All published codes, including both provide/inject symbol variants.
    pub const CODES: [&'static str; 60] = [
        "vize:croquis/cf/array-mutation",
        "vize:croquis/cf/async-boundary",
        "vize:croquis/cf/async-no-suspense",
        "vize:croquis/cf/browser-api-ssr",
        "vize:croquis/cf/circular-dep",
        "vize:croquis/cf/circular-reactive-dependency",
        "vize:croquis/cf/closure-captures-reactive",
        "vize:croquis/cf/composable-outside-setup",
        "vize:croquis/cf/computed-side-effects",
        "vize:croquis/cf/deep-import",
        "vize:croquis/cf/destructuring-breaks-reactivity",
        "vize:croquis/cf/di-outside-setup",
        "vize:croquis/cf/dom-access-without-next-tick",
        "vize:croquis/cf/duplicate-id",
        "vize:croquis/cf/event-listener-leak",
        "vize:croquis/cf/event-modifier",
        "vize:croquis/cf/hydration-risk",
        "vize:croquis/cf/inherit-attrs-unused",
        "vize:croquis/cf/inject-without-symbol",
        "vize:croquis/cf/injected-async-mutation-race",
        "vize:croquis/cf/lifecycle-outside-setup",
        "vize:croquis/cf/lifecycle-without-cleanup",
        "vize:croquis/cf/missing-required-prop",
        "vize:croquis/cf/missing-suspense",
        "vize:croquis/cf/module-scope-reactive",
        "vize:croquis/cf/multi-root-attrs",
        "vize:croquis/cf/mutated-after-escape",
        "vize:croquis/cf/non-reactive-provide",
        "vize:croquis/cf/non-unique-id",
        "vize:croquis/cf/object-identity-comparison",
        "vize:croquis/cf/pinia-getter",
        "vize:croquis/cf/prop-type-mismatch",
        "vize:croquis/cf/provide-inject-type",
        "vize:croquis/cf/provide-without-symbol",
        "vize:croquis/cf/reactive-export",
        "vize:croquis/cf/reactivity-outside-setup",
        "vize:croquis/cf/reassignment-breaks-reactivity",
        "vize:croquis/cf/reference-escapes-scope",
        "vize:croquis/cf/setup-context-violation",
        "vize:croquis/cf/shallow-deep-access",
        "vize:croquis/cf/spread-breaks-reactivity",
        "vize:croquis/cf/suspense-no-fallback",
        "vize:croquis/cf/template-ref-timing",
        "vize:croquis/cf/toraw-mutation",
        "vize:croquis/cf/uncaught-error",
        "vize:croquis/cf/undeclared-emit",
        "vize:croquis/cf/undeclared-prop",
        "vize:croquis/cf/undefined-slot",
        "vize:croquis/cf/unhandled-event",
        "vize:croquis/cf/unmatched-inject",
        "vize:croquis/cf/unmatched-listener",
        "vize:croquis/cf/unregistered-component",
        "vize:croquis/cf/unresolved-import",
        "vize:croquis/cf/unused-attrs",
        "vize:croquis/cf/unused-emit",
        "vize:croquis/cf/unused-provide",
        "vize:croquis/cf/value-extraction-breaks-reactivity",
        "vize:croquis/cf/watch-can-be-computed",
        "vize:croquis/cf/watcheffect-async",
        "vize:croquis/cf/watcher-outside-setup",
    ];
}
