//! Owned, structured contracts used by the six interface facets.

use super::{AlphaSchema, TypeEnvironment};
use serde::{Deserialize, Serialize};
use vize_carton::CompactString;

/// Component-level interface metadata, without script or template bodies.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct SignatureContract {
    pub schema: AlphaSchema,
    pub name: CompactString,
    pub declared_name: Option<CompactString>,
    pub generic: Option<CompactString>,
    pub component_shape: CompactString,
    pub script_setup: bool,
    pub prop_type_arguments: Option<CompactString>,
    pub emit_type_arguments: Option<CompactString>,
    pub slot_type_arguments: Option<CompactString>,
    pub exposes_complete: bool,
    pub exposes: Vec<ExposeContract>,
    pub type_dependencies: TypeEnvironment,
}

/// One public instance member recorded by `defineExpose`.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ExposeContract {
    pub name: CompactString,
    #[serde(rename = "type")]
    pub expose_type: Option<CompactString>,
}

/// One prop or model prop. A null field means the analyzer has no fact.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct PropContract {
    pub schema: AlphaSchema,
    pub name: CompactString,
    #[serde(rename = "type")]
    pub prop_type: Option<CompactString>,
    pub required: Option<bool>,
    #[serde(rename = "default")]
    pub default_value: Option<CompactString>,
    pub model_modifiers: Option<CompactString>,
    pub type_dependencies: TypeEnvironment,
}

/// One declared event, including the update event generated by a model.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct EmitContract {
    pub schema: AlphaSchema,
    pub name: CompactString,
    pub payload: Option<CompactString>,
    pub type_dependencies: TypeEnvironment,
}

/// One declared slot and its props type.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct SlotContract {
    pub schema: AlphaSchema,
    pub name: CompactString,
    pub props: Option<CompactString>,
    pub type_dependencies: TypeEnvironment,
}

/// The authoritative lattice result for an exported binding.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ReactivityContract {
    pub schema: AlphaSchema,
    pub name: CompactString,
    #[serde(rename = "type")]
    pub binding_type: Option<CompactString>,
    pub kind: Option<CompactString>,
    pub class: Option<CompactString>,
    pub verdict: CompactString,
    pub effects: Vec<CompactString>,
    pub type_dependencies: TypeEnvironment,
}

/// Resolved identity, independent of the local template spelling.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ComponentContract {
    pub schema: AlphaSchema,
    pub module: Option<CompactString>,
    pub export: CompactString,
}
